// Code generated by hertz generator.

package http

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizmethod1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizmethod2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bizmethod3Mw() []app.HandlerFunc {
	// your code...
	return nil
}
